language: php

php:
  - 7.0
  - 7.1

env:
    - DATABASE_URL="mysql://travis@127.0.0.1/dbdeploy"

before_script:
    - mysql -uroot -e "CREATE DATABASE dbdeploy" 
    - composer install

script: phpunit
